### PR TITLE
Migrate to Astro

### PR DESCRIPTION
**Pull request by yottalogical**
# Checklist

  * [x] This update has been tested thoroughly enough to ensure there are no
        functional bugs or obvious layout issues.
  * [x] This update has been tested in both desktop and mobile layouts.
  * [x] This update does not break any existing functionality, layout, or style
        rules, unless the update is explicitly intended to remove or update such
        functionality, layout, or style rules.
  * [x] This update is free of any code intended only for debugging or testing
        purposes.
  * [x] This update follows the FAMNM Website Code Style Guide.
  * [x] This update meets the visual style requirements as specified in the
        FAMNM Website Visual Style Guide, and any additional visual elements not
        previously specified in the FAMNM Website Visual Style Guide have been
        styled so as not to clash visually with the rest of the site.

# Description

Use [Astro](https://astro.build) as our static site generator instead of [Jekyll](https://jekyllrb.com).

### CODE REVIEW

**Comment by broad-well** [comment]
Thank you so much for starting this!

**Comment by yottalogical** [comment]
🦀🦀🦀 jQuery is gone! 🦀🦀🦀

**Comment by broad-well** [comment]
Remaining issues as of May 21, 2023:

- [ ] Show pop-ups describing each role in the organizational chart
- [ ] List these descriptions under the organizational chart
- [ ] The freelance mentoring image is not linked properly
- [ ] The getting-involved-as-a-U-of-M-student images are not linked properly

**Review by yottalogical — COMMENTED** [review]
Since I opened this pull request, I can't give it an approval on GitHub, but I approve it in spirit!

**Review by broad-well — APPROVED** [review]

**Pull request merged**
